package proyecto.pkg1.interfaces;
import javax.swing.JOptionPane;
import proyecto.pkg1.grafo.NodoV;

/**
 *
 * @author beatrizcardozo
 */
public class windowStock extends javax.swing.JFrame {
    
    static NodoV NodoWh;

    /**
     * Creates new form windowStock
     */
    public windowStock() {
        setUndecorated(true);
        initComponents();
        setSize(700, 600);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        showProductsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        warehouseJComboBox = new javax.swing.JComboBox<>();
        addProductButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        availableProductsTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qtyTextField = new javax.swing.JTextField();
        productTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("<  Atrás");
        backButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton.setOpaque(true);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel1.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 200, -1));

        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        jSeparator1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 40));

        showProductsButton.setBackground(new java.awt.Color(153, 204, 255));
        showProductsButton.setForeground(new java.awt.Color(0, 0, 0));
        showProductsButton.setText("Ver Productos Disponibles");
        showProductsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showProductsButton.setOpaque(true);
        showProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProductsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(showProductsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 200, 30));

        jLabel3.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione un almacen para gestionar su stock:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        warehouseJComboBox.setBackground(new java.awt.Color(204, 204, 204));
        warehouseJComboBox.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 14)); // NOI18N
        warehouseJComboBox.setForeground(new java.awt.Color(0, 0, 0));
        warehouseJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(windowMain.auxFunc.arrayWarehouseNames()));
        warehouseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(warehouseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 170, -1));

        addProductButton.setBackground(new java.awt.Color(153, 204, 255));
        addProductButton.setForeground(new java.awt.Color(0, 0, 0));
        addProductButton.setText("Añadir Producto");
        addProductButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addProductButton.setOpaque(true);
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 200, 30));

        availableProductsTextArea.setEditable(false);
        availableProductsTextArea.setBackground(new java.awt.Color(204, 204, 204));
        availableProductsTextArea.setColumns(20);
        availableProductsTextArea.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        availableProductsTextArea.setRows(2);
        availableProductsTextArea.setTabSize(10);
        jScrollPane3.setViewportView(availableProductsTextArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 390, 170));

        jLabel5.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Producto: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        qtyTextField.setBackground(new java.awt.Color(204, 204, 204));
        qtyTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        qtyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextFieldActionPerformed(evt);
            }
        });
        qtyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(qtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 120, -1));

        productTextField.setBackground(new java.awt.Color(204, 204, 204));
        productTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        productTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTextFieldActionPerformed(evt);
            }
        });
        productTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(productTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        windowMain main = new windowMain();
        main.show();
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void showProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProductsButtonActionPerformed
        String warehouseName = String.valueOf(warehouseJComboBox.getSelectedItem());
        NodoWh = windowMain.grafo.getList().Search(warehouseName);
        availableProductsTextArea.setText(NodoWh.getStock().Print());
    }//GEN-LAST:event_showProductsButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        if(windowMain.auxFunc.enabledButtons(qtyTextField, productTextField, addProductButton)){
            String product = productTextField.getText();
            int qty= Integer.parseInt(qtyTextField.getText());
            if(windowMain.auxFunc.searchProduct(product) != null){
                JOptionPane.showMessageDialog(this, "Producto en el inventario: se le ha sumado a su stock!");
                windowMain.auxFunc.searchProduct(product).addStock(qty);
            } else {
                NodoWh.newStockP(product, qty); }
            availableProductsTextArea.setText(NodoWh.getStock().Print());
        }  
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void warehouseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseJComboBoxActionPerformed

    private void qtyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTextFieldActionPerformed

    private void qtyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextFieldKeyTyped
        windowMain.auxFunc.verifyInt(evt, qtyTextField, 9);
    }//GEN-LAST:event_qtyTextFieldKeyTyped

    private void productTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTextFieldActionPerformed

    private void productTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productTextFieldKeyTyped
        windowMain.auxFunc.verifyString(evt, productTextField, 10);
    }//GEN-LAST:event_productTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windowStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JTextArea availableProductsTextArea;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField productTextField;
    private javax.swing.JTextField qtyTextField;
    private javax.swing.JButton showProductsButton;
    private javax.swing.JComboBox<String> warehouseJComboBox;
    // End of variables declaration//GEN-END:variables
}
