package proyecto.pkg1.interfaces;

import javax.swing.JOptionPane;
import proyecto.pkg1.grafo.NodoV;

/**
 *
 * @author beatrizcardozo
 */
public class windowWarehouse extends javax.swing.JFrame {

    /**
     * Creates new form windowAlmacen
     */
    public windowWarehouse() {
        setUndecorated(true);
        initComponents();
        setSize(700, 600);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstwhDistanceTextField = new javax.swing.JTextField();
        addWarehouseButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        secondwhJComboBox = new javax.swing.JComboBox<>();
        firstwhJComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        warehouseNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        secondwhDistanceTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        jSeparator1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 40));

        jLabel1.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Almacenes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 260, -1));

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("<  Atrás");
        backButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton.setOpaque(true);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel7.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Para añadir un nuevo almacen, ingrese los siguientes datos:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese los Almacenes Cercanos y sus respectivas distancias:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        firstwhDistanceTextField.setBackground(new java.awt.Color(204, 204, 204));
        firstwhDistanceTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        firstwhDistanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstwhDistanceTextFieldActionPerformed(evt);
            }
        });
        firstwhDistanceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstwhDistanceTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(firstwhDistanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 70, -1));

        addWarehouseButton.setBackground(new java.awt.Color(153, 204, 255));
        addWarehouseButton.setForeground(new java.awt.Color(0, 0, 0));
        addWarehouseButton.setText("Añadir Almacen");
        addWarehouseButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addWarehouseButton.setOpaque(true);
        addWarehouseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWarehouseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addWarehouseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 200, 30));

        jLabel4.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Distancia:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        secondwhJComboBox.setBackground(new java.awt.Color(204, 204, 204));
        secondwhJComboBox.setForeground(new java.awt.Color(0, 0, 0));
        secondwhJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(windowMain.auxFunc.arrayWarehouseNames()));
        jPanel1.add(secondwhJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 160, -1));

        firstwhJComboBox.setBackground(new java.awt.Color(204, 204, 204));
        firstwhJComboBox.setForeground(new java.awt.Color(0, 0, 0));
        firstwhJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(windowMain.auxFunc.arrayWarehouseNames()));
        jPanel1.add(firstwhJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 160, -1));

        jLabel5.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("km.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        warehouseNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        warehouseNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        warehouseNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseNameTextFieldActionPerformed(evt);
            }
        });
        warehouseNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                warehouseNameTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(warehouseNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 220, -1));

        jLabel8.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Distancia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        secondwhDistanceTextField.setBackground(new java.awt.Color(204, 204, 204));
        secondwhDistanceTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        secondwhDistanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondwhDistanceTextFieldActionPerformed(evt);
            }
        });
        secondwhDistanceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secondwhDistanceTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(secondwhDistanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 70, -1));

        jLabel9.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("km.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        windowMain main = new windowMain();
        main.show();
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void firstwhDistanceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstwhDistanceTextFieldKeyTyped
        windowMain.auxFunc.verifyInt(evt, firstwhDistanceTextField, 3);
    }//GEN-LAST:event_firstwhDistanceTextFieldKeyTyped

    private void addWarehouseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWarehouseButtonActionPerformed
        if(String.valueOf(firstwhJComboBox.getSelectedItem()).equals(secondwhJComboBox.getSelectedItem())){
            JOptionPane.showMessageDialog(this, "Importante: Debes ingresar dos almacenes diferentes.");
        } else {
            if(windowMain.auxFunc.enabledButtons(firstwhDistanceTextField, firstwhDistanceTextField, addWarehouseButton)){
//            boolean found = false;
//            String nombreAlmacen = firstwhDistanceTextField.getText(); 
//            if(windowMain.grafo.getList().Search(nombreAlmacen) != null){
//                found = true;
//            }
//            if(found){
//                JOptionPane.showMessageDialog(this, "Importante: Este almacen ya esta registrado!");
//            } else {
//                windowMain.grafo.getList().Insert(nombreAlmacen);
//            }
        }
        
        }
        
    }//GEN-LAST:event_addWarehouseButtonActionPerformed

    private void firstwhDistanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstwhDistanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstwhDistanceTextFieldActionPerformed

    private void warehouseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseNameTextFieldActionPerformed

    private void warehouseNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_warehouseNameTextFieldKeyTyped
        windowMain.auxFunc.verifyString(evt, warehouseNameTextField, 10);
    }//GEN-LAST:event_warehouseNameTextFieldKeyTyped

    private void secondwhDistanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondwhDistanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondwhDistanceTextFieldActionPerformed

    private void secondwhDistanceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secondwhDistanceTextFieldKeyTyped
         windowMain.auxFunc.verifyInt(evt, secondwhDistanceTextField, 3);
    }//GEN-LAST:event_secondwhDistanceTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windowWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windowWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windowWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windowWarehouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWarehouseButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField firstwhDistanceTextField;
    private javax.swing.JComboBox<String> firstwhJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField secondwhDistanceTextField;
    private javax.swing.JComboBox<String> secondwhJComboBox;
    private javax.swing.JComboBox<String> warehouseJComboBox;
    private javax.swing.JComboBox<String> warehouseJComboBox1;
    private javax.swing.JTextField warehouseNameTextField;
    // End of variables declaration//GEN-END:variables
}
