/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.interfaces;

import proyecto.pkg1.grafo.NodoV;

/**
 *
 * @author beatrizcardozo
 */
public class windowStock extends javax.swing.JFrame {
    
    static NodoV NodoAlmacen;

    /**
     * Creates new form windowStock
     */
    public windowStock() {
        setUndecorated(true);
        initComponents();
        setSize(700, 600);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        verproductosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        almacenesSelc = new javax.swing.JComboBox<>();
        añadirButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        productosTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantidadTextField = new javax.swing.JTextField();
        productoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("<  Atrás");
        backButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton.setOpaque(true);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel1.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 200, -1));

        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        jSeparator1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 40));

        verproductosButton.setBackground(new java.awt.Color(153, 204, 255));
        verproductosButton.setForeground(new java.awt.Color(0, 0, 0));
        verproductosButton.setText("Ver Productos Disponibles");
        verproductosButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        verproductosButton.setOpaque(true);
        verproductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verproductosButtonActionPerformed(evt);
            }
        });
        jPanel1.add(verproductosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 200, 30));

        jLabel3.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione un almacen para gestionar su stock:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        almacenesSelc.setBackground(new java.awt.Color(204, 204, 204));
        almacenesSelc.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 14)); // NOI18N
        almacenesSelc.setForeground(new java.awt.Color(0, 0, 0));
        almacenesSelc.setModel(new javax.swing.DefaultComboBoxModel<>(windowMain.auxFunc.almacenNames()));
        almacenesSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenesSelcActionPerformed(evt);
            }
        });
        jPanel1.add(almacenesSelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 170, -1));

        añadirButton.setBackground(new java.awt.Color(153, 204, 255));
        añadirButton.setForeground(new java.awt.Color(0, 0, 0));
        añadirButton.setText("Añadir Producto");
        añadirButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        añadirButton.setOpaque(true);
        añadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(añadirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 200, 30));

        productosTextArea.setEditable(false);
        productosTextArea.setBackground(new java.awt.Color(204, 204, 204));
        productosTextArea.setColumns(20);
        productosTextArea.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 13)); // NOI18N
        productosTextArea.setRows(2);
        productosTextArea.setTabSize(10);
        jScrollPane3.setViewportView(productosTextArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 390, 170));

        jLabel5.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Producto: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        cantidadTextField.setBackground(new java.awt.Color(204, 204, 204));
        cantidadTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cantidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTextFieldActionPerformed(evt);
            }
        });
        cantidadTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(cantidadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 120, -1));

        productoTextField.setBackground(new java.awt.Color(204, 204, 204));
        productoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        productoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoTextFieldActionPerformed(evt);
            }
        });
        productoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(productoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        windowMain main = new windowMain();
        main.show();
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void verproductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verproductosButtonActionPerformed
        String nombreAlmacen = String.valueOf(almacenesSelc.getSelectedItem());
        NodoAlmacen = windowMain.grafo.getList().Search(nombreAlmacen);
        productosTextArea.setText(NodoAlmacen.getStock().Print());
    }//GEN-LAST:event_verproductosButtonActionPerformed

    private void añadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirButtonActionPerformed
        if(windowMain.auxFunc.enabledButtons(cantidadTextField, productoTextField, añadirButton)){
            String producto = productoTextField.getText();
            int cantidad = Integer.parseInt(cantidadTextField.getText());

            if(NodoAlmacen.getStock().getpFirst().equals(producto)){
                
            } else {
                NodoAlmacen.newStockP(producto, cantidad);
                productosTextArea.setText(NodoAlmacen.getStock().Print());
            }
            
            
        }
        
    }//GEN-LAST:event_añadirButtonActionPerformed

    private void almacenesSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenesSelcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenesSelcActionPerformed

    private void cantidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTextFieldActionPerformed

    private void cantidadTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTextFieldKeyTyped
        windowMain.auxFunc.verifyInt(evt, cantidadTextField, 9);
    }//GEN-LAST:event_cantidadTextFieldKeyTyped

    private void productoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoTextFieldActionPerformed

    private void productoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoTextFieldKeyTyped
        windowMain.auxFunc.verifyString(evt, productoTextField, 10);
    }//GEN-LAST:event_productoTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windowStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> almacenesSelc;
    private javax.swing.JButton añadirButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cantidadTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField productoTextField;
    private javax.swing.JTextArea productosTextArea;
    private javax.swing.JButton verproductosButton;
    // End of variables declaration//GEN-END:variables
}
